export const AUDIO_CHUNK_DURATION_MS = 5000;
export const AUDIO_PROCESSING_DELAY_MS = 250;
export const MIN_AUDIO_FILE_SIZE_BYTES = 8_000;
export const MIN_TRANSCRIPT_LENGTH = 4;
export const RECENT_TRANSCRIPT_MEMORY_SIZE = 8;
export const TRANSCRIPT_SIMILARITY_THRESHOLD = 0.88;
export const DUPLICATE_TRANSCRIPT_WINDOW_MS = 20_000;
